---
- hosts: all
  tasks:
  - name: Update apt cache on machine
    become: true
    apt:
      update_cache: yes
      upgrade: yes

  - name: Copy correct sshd_config to machines
    become: true
    copy:
      src: sshd_config
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: '0644'
    notify:
      - Restart sshd

  - name: Install git and python-pip
    become: true
    apt:
      pkg:
      - git
      - python-pip
      - python3-pip
      update_cache: yes
      state: present

  - name: Upgrade pip3
    become: true
    pip:
      name: pip
      executable: pip3
      extra_args: --upgrade
    tags: pip, python3

  - name: Set root password to 'root'
    become: true
    user:
      name: root
      password: "{{ root_password | password_hash('sha512') }}"
      update_password: always

  - name: Set authorizd ssh key for user 'vagrant'
    become: true
    authorized_key:
      user: vagrant
      state: present
      key: "{{ lookup('file', '{{ item }}') }}"
    loop: "{{ ssh_keys }}"

  - name: Set authorizd ssh key for user 'root'
    become: true
    authorized_key:
      user: root
      state: present
      key: "{{ lookup('file', '{{ item }}') }}"
    loop: "{{ ssh_keys }}"


  handlers:
  - name: Restart sshd
    become: true
    command: systemctl restart sshd

