all:
  hosts:
    ansible-host:
    simple-node:
    node[1:3]:
  children:
    nodes:
      hosts:
        node[1:3]:
    node-setup:
      hosts:
        simple-node:
    master:
      hosts:
        ansible-host: