# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
BOX_IMAGE = "ubuntu/bionic64"
NODE_COUNT = 3

Vagrant.configure("2") do |config|


  config.vm.define "ansible-host" do |ans|
    ans.vm.box = BOX_IMAGE
    ans.vm.hostname = "ansible-host"
    ans.vm.network "private_network", ip: "192.168.33.10"
    ans.vm.provision :ansible do |ansible|
      ansible.playbook = "ansible-host.yml"
    end
  end

  (1..NODE_COUNT).each do |i|
    config.vm.define "node#{i}" do |subans|
      subans.vm.box = BOX_IMAGE
      subans.vm.hostname = "node#{i}"
      subans.vm.network "private_network", ip: "192.168.33.#{i * 10 + 10}"
      subans.vm.provision :ansible do |ansible|
        ansible.playbook = "basic-setup.yml"
      end
    end
  end
end
