# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|


  config.vm.define "ansible-host" do |ans|
    ans.vm.box = "ubuntu/bionic64"
    ans.vm.network "private_network", ip: "192.168.33.10"
    ans.vm.provision :ansible do |ansible|
      ansible.playbook = "ansible-host.yml"
    end
  end

  config.vm.define "node1" do |ans|
    ans.vm.box = "ubuntu/bionic64"
    ans.vm.network "private_network", ip: "192.168.33.20"
  end

  config.vm.define "node2" do |ans|
    ans.vm.box = "ubuntu/bionic64"
    ans.vm.network "private_network", ip: "192.168.33.30"
  end

  config.vm.define "node3" do |ans|
    ans.vm.box = "ubuntu/bionic64"
    ans.vm.network "private_network", ip: "192.168.33.40"
  end


end
